package classify_test

import (
	"reflect"
	"testing"

	"github.com/aplotnikov/guided-review/internal/classify"
)

func TestGenerated(t *testing.T) {
	c := classify.New(classify.DefaultPatterns, []string{"api/gen/**", "/schema.graphql"})
	tests := []struct {
		path string
		want bool
	}{
		{"api/transfer.pb.go", true},
		{"transfer.pb.go", true},
		{"proto/transfer_pb2.py", true},
		{"go.sum", true},
		{"sub/go.sum", true},
		{"vendor/x/y.go", true},
		{"app/build/generated/Foo.kt", true},
		{"api/gen/client.go", true},
		{"schema.graphql", true},
		{"other/schema.graphql", false},
		{"api/transfer.go", false},
		{"api/pb.go", false},
	}
	for _, tt := range tests {
		if got := c.Generated(tt.path); got != tt.want {
			t.Errorf("Generated(%q) = %v, want %v", tt.path, got, tt.want)
		}
	}
}

func TestHasMarker(t *testing.T) {
	tests := []struct {
		name, content string
		want          bool
	}{
		{"go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n", true},
		{"python", "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n", true},
		{"kotlin", "/*\n * @generated\n */\npackage x\n", true},
		{"literal in code", "package x\n\nfunc f() { s := \"DO NOT EDIT\" }\n", false},
		{"plain", "package x\n", false},
	}
	for _, tt := range tests {
		if got := classify.HasMarker(tt.content); got != tt.want {
			t.Errorf("%s: HasMarker = %v, want %v", tt.name, got, tt.want)
		}
	}
}

func TestGitattributesPatterns(t *testing.T) {
	in := "# comment\n*.pb.go linguist-generated=true\ndocs/** linguist-documentation\napi/gen/** -diff linguist-generated\n"
	want := []string{"*.pb.go", "api/gen/**"}
	if got := classify.GitattributesPatterns(in); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}
