package classify_test

import (
	"reflect"
	"testing"

	"github.com/pltanton/guided-review/internal/classify"
)

func TestGenerated(t *testing.T) {
	c := classify.New(
		classify.Set{Source: "default", Patterns: classify.DefaultPatterns},
		classify.Set{Source: "config", Patterns: []string{"api/gen/**", "/schema.graphql"}},
	)
	tests := []struct {
		path, want string
	}{
		{"api/transfer.pb.go", "default *.pb.go"},
		{"transfer.pb.go", "default *.pb.go"},
		{"proto/transfer_pb2.py", "default *_pb2.py"},
		{"go.sum", "default go.sum"},
		{"sub/go.sum", "default go.sum"},
		{"vendor/x/y.go", "default vendor/**"},
		{"app/build/generated/Foo.kt", "default **/build/generated/**"},
		{"api/gen/client.go", "config api/gen/**"},
		{"schema.graphql", "config /schema.graphql"},
		{"other/schema.graphql", ""},
		{"api/transfer.go", ""},
		{"api/pb.go", ""},
	}
	for _, tt := range tests {
		if got := c.Match(tt.path); got != tt.want {
			t.Errorf("Match(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestMarker(t *testing.T) {
	goMarker := "// Code generated by protoc-gen-go. DO NOT EDIT."
	tests := []struct {
		name, content, want string
	}{
		{"go", goMarker + "\npackage api\n", "marker " + goMarker},
		{"go after build tag", "//go:build linux\n\n" + goMarker + "\n", "marker " + goMarker},
		{"go after package", "package api\n\n" + goMarker + "\n", ""},
		{"go without the dot", "// Code generated by x. DO NOT EDIT\n", ""},
		{"sql warning", "-- DO NOT EDIT after release\nCREATE TABLE t ();\n", ""},
		{"config warning", "# DO NOT EDIT: deployed by hand\nkey: 1\n", ""},
		{"python protobuf", "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n", ""},
		{"kotlin block", "/*\n * @generated\n */\npackage x\n", "marker * @generated"},
		{"cargo", "# This file is automatically @generated by Cargo.\n", "marker # This file is automatically @generated by Cargo."},
		{"after shebang", "#!/bin/sh\n# @generated by gen.sh\n", "marker # @generated by gen.sh"},
		{"second comment line", "// Copyright 2024\n// @generated\n", ""},
		{"literal in code", "package x\n\nfunc f() { s := \"DO NOT EDIT\" }\n", ""},
		{"plain", "package x\n", ""},
	}
	for _, tt := range tests {
		if got := classify.Marker(tt.content); got != tt.want {
			t.Errorf("%s: Marker = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestGitattributesPatterns(t *testing.T) {
	in := "# comment\n*.pb.go linguist-generated=true\ndocs/** linguist-documentation\napi/gen/** -diff linguist-generated\n"
	want := []string{"*.pb.go", "api/gen/**"}
	if got := classify.GitattributesPatterns(in); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}
