package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/pltanton/guided-review/internal/inbox"
	"github.com/pltanton/guided-review/internal/testrepo"
)

type harness struct {
	t     *testing.T
	repo  *testrepo.Repo
	cache string
	glab  func(context.Context, ...string) ([]byte, error)
}

func newHarness(t *testing.T) *harness {
	tr := testrepo.New(t)
	tr.Write(
		"api/transfer.go",
		"package api\n\nfunc Transfer(a, b int) int {\n\treturn a + b\n}\n",
	)
	tr.Commit("base")
	tr.Git("checkout", "-q", "-b", "feature")
	tr.Write(
		"api/transfer.go",
		"package api\n\nfunc Transfer(a, b int) int {\n\tif a < 0 {\n\t\treturn 0\n\t}\n\treturn a + b\n}\n",
	)
	tr.Write(
		"api/transfer.pb.go",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
	)
	tr.Write("wire.go", "package api\n\nvar _ = Transfer\n")
	tr.Commit("guard")
	return &harness{t: t, repo: tr, cache: t.TempDir()}
}

func (h *harness) run(stdin string, args ...string) (string, error) {
	h.t.Helper()
	var out bytes.Buffer
	err := run(
		context.Background(),
		env{
			dir:       h.repo.Dir,
			cacheDir:  h.cache,
			exportDir: filepath.Join(h.cache, "export"),
			stdin:     strings.NewReader(stdin),
			stdout:    &out,
			glab:      h.glab,
		},
		args,
	)
	return out.String(), err
}

func (h *harness) mustRun(stdin string, args ...string) string {
	h.t.Helper()
	out, err := h.run(stdin, args...)
	if err != nil {
		h.t.Fatalf("gr %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return out
}

func assertContains(t *testing.T, out string, wants ...string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(out, w) {
			t.Fatalf("output lacks %q:\n%s", w, out)
		}
	}
}

func TestInitBranch(t *testing.T) {
	h := newHarness(t)
	out := h.mustRun("", "init")
	assertContains(
		t,
		out,
		"review feature",
		"api/transfer.go  [modified]  4-6",
		"wire.go  [added]  1-3",
		"generated (1 files, not reviewed)",
		"api/transfer.pb.go",
	)

	out = h.mustRun("", "init")
	assertContains(t, out, "already exists, resuming")

	out = h.mustRun("", "hunks")
	assertContains(t, out, "api/transfer.go  [modified]  4-6")
}

func TestInitOtherBranchUsesWorktree(t *testing.T) {
	h := newHarness(t)
	feature := h.repo.Git("rev-parse", "feature")
	h.repo.Git("checkout", "-q", "main")
	out := h.mustRun("", "init", "feature")
	wt := filepath.Join(h.cache, "guided-review", filepath.Base(h.repo.Dir)+"-feature")
	assertContains(t, out, "review feature", "code: "+wt)
	if got := h.repo.Git("-C", wt, "rev-parse", "HEAD"); got != feature {
		t.Fatalf("worktree HEAD = %s, want %s", got, feature)
	}
	if got := h.repo.Git("rev-parse", "--abbrev-ref", "HEAD"); got != "main" {
		t.Fatalf("user HEAD moved to %s", got)
	}

	out = h.mustRun("", "list")
	assertContains(t, out, "* feature")

	h.mustRun("", "done")
	if _, err := os.Stat(wt); !os.IsNotExist(err) {
		t.Fatalf("worktree not removed: %v", err)
	}
	if _, err := h.run("", "status"); err == nil {
		t.Fatal("status after done must fail: no active review")
	}
}

func TestInitMR(t *testing.T) {
	h := newHarness(t)
	base := h.repo.Git("rev-parse", "main")
	head := h.repo.Git("rev-parse", "HEAD")
	discussions := `[{"id":"d1","notes":[{"body":"why 0 and not an error?","author":{"username":"alice"},"system":false,"resolvable":true,
		"position":{"new_path":"api/transfer.go","new_line":5,"old_path":"api/transfer.go"}}]},
		{"id":"d2","notes":[{"body":"please add a test","author":{"username":"bob"},"system":false,"resolvable":true}]}]`
	h.glab = func(_ context.Context, args ...string) ([]byte, error) {
		if strings.Contains(args[len(args)-1], "/discussions") {
			return []byte(discussions), nil
		}
		return []byte(
			fmt.Sprintf(
				`{"title":"Add guard","web_url":"https://h/g/p/-/merge_requests/7","source_branch":"feature",
			"diff_refs":{"base_sha":%q,"start_sha":%q,"head_sha":%q}}`,
				base,
				base,
				head,
			),
		), nil
	}
	out := h.mustRun("", "init", "https://h/g/p/-/merge_requests/7")
	assertContains(
		t,
		out,
		"review mr-7",
		"MR !7 Add guard",
		"MR discussions: 2 unresolved",
		"@bob: please add a test",
		"@alice api/transfer.go:5: why 0 and not an error?",
	)

	out = h.mustRun("", "discussions")
	assertContains(t, out, "@bob (0 replies)\n  please add a test")
	discussions = `[]`
	if out = h.mustRun("", "discussions"); out != "" {
		t.Fatalf("no discussions left, got %q", out)
	}
}

const goodPlan = `summary: negative amounts are rejected
boilerplate: [wire.go]
steps:
  - id: s1
    title: Transfer guard
    kind: logic
    hunks: [{file: api/transfer.go}]
    hotspots: [{cat: money, q: "0 for a negative amount — expected?"}]
  - id: s2
    title: Guard follow-up
    kind: logic
    hunks: [{file: api/transfer.go, lines: 7-8}]
    depends_on: [s1]
`

func TestReviewLoop(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")

	_, err := h.run(
		"steps:\n  - id: s1\n    title: x\n    kind: logic\n    hunks: [{file: api/transfer.go, lines: 1-2}]\n",
		"plan",
		"set",
	)
	if err == nil || !strings.Contains(err.Error(), "not covered: api/transfer.go:4-6") ||
		!strings.Contains(err.Error(), "not covered: wire.go:1-3") {
		t.Fatalf("want coverage rejection, got %v", err)
	}

	out := h.mustRun(goodPlan, "plan", "set")
	assertContains(
		t,
		out,
		"plan accepted: 2 steps",
		"s1 1/2 [pending] logic · Transfer guard",
		"hotspot money",
	)

	out = h.mustRun(
		"",
		"comment",
		"add",
		"--file",
		"api/transfer.go",
		"--lines",
		"4-6",
		"--severity",
		"blocker",
		"reject",
		"negative",
		"amounts",
	)
	assertContains(
		t,
		out,
		"comment #1 blocker api/transfer.go:4-6",
		"stale (depend on a blocked step): s2",
	)

	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 blocker s1 api/transfer.go:4-6  reject negative amounts")

	_, err = h.run("", "status", "--gate")
	if err == nil {
		t.Fatal("gate must fail with s1 pending")
	}

	out = h.mustRun("", "step", "next")
	assertContains(t, out, "all steps reviewed")

	out = h.mustRun("", "status", "--gate")
	assertContains(
		t,
		out,
		"✓ s1",
		"~ s2",
		"core 1/2 reviewed (0 skipped, 1 stale)",
		"hotspots 1/1",
		"boilerplate 1 files",
		"generated 1 files",
		"1 blocker",
		"gate: passed",
	)

	out = h.mustRun("", "step", "goto", "s2")
	assertContains(t, out, "s2 2/2 [stale]")
}

func TestStepSkip(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	if _, err := h.run("", "step", "skip"); err == nil {
		t.Fatal("skip without reason must fail")
	}
	out := h.mustRun("", "step", "skip", "--reason", "trivial")
	assertContains(t, out, "s2 2/2 [pending]")
	out = h.mustRun("", "step", "show", "s1")
	assertContains(t, out, "[skipped]", "skipped: trivial")
}

func TestNotesAndResolve(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	out := h.mustRun(
		"",
		"note",
		"add",
		"--file",
		"api/transfer.go",
		"--line",
		"4",
		"guard",
		"for",
		"negatives",
	)
	assertContains(t, out, "note s1 api/transfer.go:4")
	out = h.mustRun("", "step", "show")
	assertContains(t, out, "note api/transfer.go:4: guard for negatives")

	h.mustRun(
		"",
		"comment",
		"add",
		"--file",
		"api/transfer.go",
		"--lines",
		"5",
		"--severity",
		"nit",
		"x",
	)
	out = h.mustRun("", "comment", "resolve", "1")
	assertContains(t, out, "comment #1 resolved")
	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 nit s1 api/transfer.go:5  x  [resolved]")
}

func TestReReviewFixup(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	h.mustRun(
		"",
		"comment",
		"add",
		"--file",
		"api/transfer.go",
		"--lines",
		"5",
		"--severity",
		"major",
		"return an error",
	)
	h.mustRun("", "step", "next")

	h.repo.Write("wire.go", "package api\n\nvar _ = Transfer\nvar _ = 1\n")
	h.repo.Commit("fixup")

	out := h.mustRun("", "init")
	assertContains(
		t,
		out,
		"round 2: fixups since",
		"open comments from earlier rounds: 1",
		"#1 major api/transfer.go:5  return an error",
		"wire.go  [modified]  4",
	)
	if strings.Contains(out, "api/transfer.go  [") {
		t.Fatalf("round 2 must only show the fixup diff:\n%s", out)
	}
	_, err := h.run(
		"steps:\n  - id: r1\n    title: x\n    kind: logic\n    hunks: [{file: api/transfer.go}]\n",
		"plan",
		"set",
	)
	if err == nil || !strings.Contains(err.Error(), "not in diff") {
		t.Fatalf("round 2 plan over an unchanged file must be rejected, got %v", err)
	}
	out = h.mustRun(
		"steps:\n  - id: r1\n    title: fixup\n    kind: logic\n    hunks: [{file: wire.go}]\n",
		"plan",
		"set",
	)
	assertContains(t, out, "plan accepted: 1 steps")
	h.mustRun("", "comment", "resolve", "1")
	out = h.mustRun("", "status")
	assertContains(t, out, "round 2")
}

func TestReReviewRebase(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")

	h.repo.Git("checkout", "-q", "main")
	h.repo.Write("other.go", "package api\n")
	h.repo.Commit("upstream")
	h.repo.Git("checkout", "-q", "feature")
	h.repo.Git("rebase", "-q", "main")
	h.repo.Write("wire.go", "package api\n\nvar _ = Transfer\nvar _ = 2\n")
	h.repo.Git("commit", "-q", "-a", "--amend", "--no-edit")

	out := h.mustRun("", "init")
	assertContains(t, out, "round 2: rebased, changed files: wire.go")
	_, err := h.run(
		"steps:\n  - id: r1\n    title: x\n    kind: logic\n    hunks: [{file: api/transfer.go}]\n",
		"plan",
		"set",
	)
	if err == nil || !strings.Contains(err.Error(), "not covered: wire.go") {
		t.Fatalf("want wire.go coverage error, got %v", err)
	}
	out = h.mustRun(
		"steps:\n  - id: r1\n    title: wire\n    kind: logic\n    hunks: [{file: wire.go}]\n",
		"plan",
		"set",
	)
	assertContains(t, out, "plan accepted: 1 steps")
}

func TestWaitAndSay(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")

	s, r, err := loadReview(context.Background(), h.repo.Dir)
	if err != nil {
		t.Fatal(err)
	}
	ev := inbox.Event{
		Kind: inbox.KindMessage, Step: "s1", File: "api/transfer.go", Lines: "4", Text: "why 0?",
	}
	if err := inbox.Append(s.store.ReviewDir(r.ID), ev); err != nil {
		t.Fatal(err)
	}
	out := h.mustRun("", "wait", "--timeout", "1s")
	assertContains(t, out, "[message] s1 api/transfer.go:4: why 0?")
	out = h.mustRun("", "wait", "--timeout", "50ms")
	assertContains(t, out, "no input yet")

	h.mustRun("", "say", "Zero", "is", "a", "silent", "reject.")
	_, r, _ = loadReview(context.Background(), h.repo.Dir)
	if n := len(r.Messages); n != 1 || r.Messages[0].Text != "Zero is a silent reject." ||
		r.Messages[0].Step != "s1" {
		t.Fatalf("messages: %+v", r.Messages)
	}
}

func TestForceKeepsComments(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	h.mustRun(
		"",
		"comment",
		"add",
		"--file",
		"api/transfer.go",
		"--lines",
		"5",
		"--severity",
		"major",
		"return an error",
	)
	out := h.mustRun("", "init", "--force")
	assertContains(t, out, "kept 1 comments")
	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 major s1 api/transfer.go:5  return an error")
}

func TestDiscussionsFull(t *testing.T) {
	h := newHarness(t)
	base := h.repo.Git("rev-parse", "main")
	head := h.repo.Git("rev-parse", "HEAD")
	h.glab = func(_ context.Context, args ...string) ([]byte, error) {
		if strings.Contains(args[len(args)-1], "/discussions") {
			return []byte(
				`[{"id":"d1","notes":[{"body":"## acc-guard\nline two\nline three","author":{"username":"ci"},"system":false,"resolvable":true},
				{"body":"reply","author":{"username":"bob"},"system":false}]}]`,
			), nil
		}
		return []byte(
			fmt.Sprintf(
				`{"title":"T","web_url":"u","diff_refs":{"base_sha":%q,"start_sha":%q,"head_sha":%q}}`,
				base,
				base,
				head,
			),
		), nil
	}
	h.mustRun("", "init", "https://h/g/p/-/merge_requests/7")
	out := h.mustRun("", "discussions")
	assertContains(t, out, "@ci (1 replies)", "## acc-guard\n  line two\n  line three")
}

func TestProgress(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun("", "progress", "строю", "план")
	_, r, _ := loadReview(context.Background(), h.repo.Dir)
	if r.Progress == nil || r.Progress.Text != "строю план" {
		t.Fatalf("progress: %+v", r.Progress)
	}
}

func TestIdleCommand(t *testing.T) {
	h := newHarness(t)
	if _, err := h.run("", "idle"); err != nil {
		t.Fatalf("idle without a review must be a silent no-op: %v", err)
	}
	h.mustRun("", "init")
	h.mustRun("", "idle")
	s, r, _ := loadReview(context.Background(), h.repo.Dir)
	if _, ok := inbox.IdleSince(s.store.ReviewDir(r.ID)); !ok {
		t.Fatal("idle marker not written")
	}
}

func TestCommentEdit(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	h.mustRun(
		"",
		"comment",
		"add",
		"--file",
		"api/transfer.go",
		"--lines",
		"5",
		"--severity",
		"nit",
		"x",
	)
	out := h.mustRun("", "comment", "edit", "1", "--severity", "major", "return", "an", "error")
	assertContains(t, out, "comment #1 updated")
	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 major s1 api/transfer.go:5  return an error")
}

func mrHarness(t *testing.T) (*harness, *[]string) {
	h := newHarness(t)
	base := h.repo.Git("rev-parse", "main")
	head := h.repo.Git("rev-parse", "HEAD")
	var calls []string
	h.glab = func(_ context.Context, args ...string) ([]byte, error) {
		path := args[len(args)-1]
		calls = append(calls, path)
		if strings.Contains(path, "/discussions") {
			return []byte(`[]`), nil
		}
		return fmt.Appendf(nil, `{"title":"Add guard","web_url":"https://h/g/p/-/merge_requests/7",
			"source_branch":"feature","diff_refs":{"base_sha":%q,"start_sha":%q,"head_sha":%q}}`,
			base, base, head), nil
	}
	h.mustRun("", "init", "https://h/g/p/-/merge_requests/7")
	h.mustRun(goodPlan, "plan", "set")
	return h, &calls
}

func TestExport(t *testing.T) {
	h, calls := mrHarness(t)
	h.mustRun("", "comment", "add", "--file", "api/transfer.go", "--lines", "4-6",
		"--severity", "major", "return an error instead")
	h.mustRun("", "comment", "add", "--file", "api/transfer.go", "--lines", "7",
		"--severity", "nit", "--suggestion", "\treturn a+b", "spacing")

	prepare := []string{"prepare", "--verdict", "changes", "--decisions", "zero is a silent reject"}
	if _, err := h.run("", prepare...); err == nil || !strings.Contains(err.Error(), "gate not passed") {
		t.Fatalf("prepare before the gate must fail, got %v", err)
	}
	if _, err := h.run("", "export"); err == nil || !strings.Contains(err.Error(), "nothing prepared") {
		t.Fatalf("export before prepare must fail, got %v", err)
	}
	h.mustRun("", "step", "next")
	h.mustRun("", "step", "next")
	*calls = nil
	h.mustRun("", prepare...)

	out := h.mustRun("", "export", "--dry-run")
	assertContains(t, out, "api/transfer.go:6", "**major** return an error instead",
		"```suggestion:-0+0", "**Guided review: changes requested**", "zero is a silent reject",
		"Comments: 1 major, 1 nit, inline.")
	dir := filepath.Join(h.cache, "export", "mr-7")
	if _, err := os.Stat(dir); err == nil {
		t.Fatal("dry run must not write the export")
	}

	out = h.mustRun("", "export")
	if strings.TrimSpace(out) != dir {
		t.Fatalf("export printed %q, want %q", out, dir)
	}
	var x export
	data, err := os.ReadFile(filepath.Join(dir, "review.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, &x); err != nil {
		t.Fatal(err)
	}
	if x.API != "projects/g%2Fp/merge_requests/7" || x.Host != "h" || x.Verdict != "changes" ||
		!slices.Equal(x.Comments, []int{1, 2}) || !x.Summary || len(x.Drafts) != 3 {
		t.Fatalf("review.json: %+v", x)
	}
	first, err := os.ReadFile(filepath.Join(dir, x.Drafts[0]))
	if err != nil || !strings.Contains(string(first), `"new_line": 6`) {
		t.Fatalf("first draft must sit on line 6: %s %v", first, err)
	}
	for _, c := range *calls {
		if !strings.Contains(c, "/discussions") {
			t.Fatalf("gr must not write to GitLab: %v", *calls)
		}
	}

	assertContains(t, h.mustRun("", "mark-published"), "marked 2 comments published")
	if _, err := h.run("", "export", "--dry-run"); err == nil {
		t.Fatal("mark-published must clear the prepared result")
	}
	h.mustRun("", prepare...)
	if out := h.mustRun("", "export", "--dry-run"); strings.Contains(out, "---") {
		t.Fatalf("published comments and summary must not be exported again:\n%s", out)
	}
}

func TestConfigCommands(t *testing.T) {
	h := newHarness(t)
	cfgDir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", cfgDir)
	out := h.mustRun("", "config")
	assertContains(t, out, "user config:", "not created", "diff: histogram")
	out = h.mustRun("", "config", "init")
	path := filepath.Join(cfgDir, "guided-review", "config.yaml")
	assertContains(t, out, "wrote "+path)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`#   next-hunk: ["]"]`, `#   definition: ["g d"]`, "# view:", "#   context: 3",
	} {
		if !strings.Contains(string(data), want) {
			t.Fatalf("template lacks %q:\n%s", want, data)
		}
	}
	if _, err := h.run("", "config", "init"); err == nil {
		t.Fatal("config init must not overwrite an existing file")
	}
	if err := os.WriteFile(path, []byte("keys:\n  next-hunk: [j]\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out = h.mustRun("", "config")
	assertContains(t, out, "key conflicts")
}

func TestSelfReview(t *testing.T) {
	h := newHarness(t)
	out := h.mustRun("", "init", "--self")
	assertContains(t, out, "review self-feature", "mode: self")
	h.mustRun(goodPlan, "plan", "set")
	h.mustRun("", "comment", "add", "--file", "api/transfer.go", "--lines", "4",
		"--severity", "minor", "--suggestion", "\tif a <= 0 {", "zero is negative too")
	h.mustRun("", "step", "next")
	h.mustRun("", "step", "next")
	h.mustRun("", "prepare", "--verdict", "changes", "--decisions", "fix the guard")

	assertContains(t, h.mustRun("", "export", "--dry-run"),
		"--- api/transfer.go:4", "**minor** zero is negative too", "```suggestion", "--- summary")
	dir := filepath.Join(h.cache, "export", "self-feature")
	if out := strings.TrimSpace(h.mustRun("", "export")); out != dir {
		t.Fatalf("export printed %q, want %q", out, dir)
	}
	data, err := os.ReadFile(filepath.Join(dir, "fixes.json"))
	if err != nil {
		t.Fatal(err)
	}
	var x struct {
		Verdict string `json:"verdict"`
		Fixes   []fix  `json:"fixes"`
	}
	if err := json.Unmarshal(data, &x); err != nil {
		t.Fatal(err)
	}
	want := fix{ID: 1, Severity: "minor", File: "api/transfer.go", Lines: "4",
		Body: "zero is negative too", Suggestion: "\tif a <= 0 {"}
	if x.Verdict != "changes" || len(x.Fixes) != 1 || x.Fixes[0] != want {
		t.Fatalf("fixes.json: %s", data)
	}
	if _, err := os.Stat(filepath.Join(dir, "review.json")); err == nil {
		t.Fatal("a self review must not produce GitLab drafts")
	}
}
