package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/aplotnikov/guided-review/internal/testrepo"
)

type harness struct {
	t     *testing.T
	repo  *testrepo.Repo
	cache string
	glab  func(context.Context, ...string) ([]byte, error)
}

func newHarness(t *testing.T) *harness {
	tr := testrepo.New(t)
	tr.Write("api/transfer.go", "package api\n\nfunc Transfer(a, b int) int {\n\treturn a + b\n}\n")
	tr.Commit("base")
	tr.Git("checkout", "-q", "-b", "feature")
	tr.Write("api/transfer.go", "package api\n\nfunc Transfer(a, b int) int {\n\tif a < 0 {\n\t\treturn 0\n\t}\n\treturn a + b\n}\n")
	tr.Write("api/transfer.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")
	tr.Write("wire.go", "package api\n\nvar _ = Transfer\n")
	tr.Commit("guard")
	return &harness{t: t, repo: tr, cache: t.TempDir()}
}

func (h *harness) run(stdin string, args ...string) (string, error) {
	h.t.Helper()
	var out bytes.Buffer
	err := run(context.Background(), env{dir: h.repo.Dir, cacheDir: h.cache, stdin: strings.NewReader(stdin), stdout: &out, glab: h.glab}, args)
	return out.String(), err
}

func (h *harness) mustRun(stdin string, args ...string) string {
	h.t.Helper()
	out, err := h.run(stdin, args...)
	if err != nil {
		h.t.Fatalf("gr %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return out
}

func assertContains(t *testing.T, out string, wants ...string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(out, w) {
			t.Fatalf("output lacks %q:\n%s", w, out)
		}
	}
}

func TestInitBranch(t *testing.T) {
	h := newHarness(t)
	out := h.mustRun("", "init")
	assertContains(t, out, "review feature", "api/transfer.go  [modified]  4-6", "wire.go  [added]  1-3", "generated (1 files, not reviewed)", "api/transfer.pb.go")

	out = h.mustRun("", "init")
	assertContains(t, out, "already exists, resuming")

	out = h.mustRun("", "hunks")
	assertContains(t, out, "api/transfer.go  [modified]  4-6")
}

func TestInitOtherBranchUsesWorktree(t *testing.T) {
	h := newHarness(t)
	feature := h.repo.Git("rev-parse", "feature")
	h.repo.Git("checkout", "-q", "main")
	out := h.mustRun("", "init", "feature")
	wt := filepath.Join(h.cache, "guided-review", filepath.Base(h.repo.Dir)+"-feature")
	assertContains(t, out, "review feature", "code: "+wt)
	if got := h.repo.Git("-C", wt, "rev-parse", "HEAD"); got != feature {
		t.Fatalf("worktree HEAD = %s, want %s", got, feature)
	}
	if got := h.repo.Git("rev-parse", "--abbrev-ref", "HEAD"); got != "main" {
		t.Fatalf("user HEAD moved to %s", got)
	}

	out = h.mustRun("", "list")
	assertContains(t, out, "* feature")

	h.mustRun("", "done")
	if _, err := os.Stat(wt); !os.IsNotExist(err) {
		t.Fatalf("worktree not removed: %v", err)
	}
	if _, err := h.run("", "status"); err == nil {
		t.Fatal("status after done must fail: no active review")
	}
}

func TestInitMR(t *testing.T) {
	h := newHarness(t)
	base := h.repo.Git("rev-parse", "main")
	head := h.repo.Git("rev-parse", "HEAD")
	h.glab = func(_ context.Context, args ...string) ([]byte, error) {
		return []byte(fmt.Sprintf(`{"title":"Add guard","web_url":"https://h/g/p/-/merge_requests/7","source_branch":"feature",
			"diff_refs":{"base_sha":%q,"start_sha":%q,"head_sha":%q}}`, base, base, head)), nil
	}
	out := h.mustRun("", "init", "https://h/g/p/-/merge_requests/7")
	assertContains(t, out, "review mr-7", "MR !7 Add guard")
}

const goodPlan = `summary: negative amounts are rejected
boilerplate: [wire.go]
steps:
  - id: s1
    title: Transfer guard
    kind: logic
    hunks: [{file: api/transfer.go}]
    hotspots: [{cat: money, q: "0 for a negative amount — expected?"}]
  - id: s2
    title: Guard follow-up
    kind: logic
    hunks: [{file: api/transfer.go, lines: 7-8}]
    depends_on: [s1]
`

func TestReviewLoop(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")

	_, err := h.run("steps:\n  - id: s1\n    title: x\n    kind: logic\n    hunks: [{file: api/transfer.go, lines: 1-2}]\n", "plan", "set")
	if err == nil || !strings.Contains(err.Error(), "not covered: api/transfer.go:4-6") || !strings.Contains(err.Error(), "not covered: wire.go:1-3") {
		t.Fatalf("want coverage rejection, got %v", err)
	}

	out := h.mustRun(goodPlan, "plan", "set")
	assertContains(t, out, "plan accepted: 2 steps", "s1 1/2 [pending] logic · Transfer guard", "hotspot money")

	out = h.mustRun("", "comment", "add", "--file", "api/transfer.go", "--lines", "4-6", "--severity", "blocker", "reject", "negative", "amounts")
	assertContains(t, out, "comment #1 blocker api/transfer.go:4-6", "stale (depend on a blocked step): s2")

	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 blocker s1 api/transfer.go:4-6  reject negative amounts")

	_, err = h.run("", "status", "--gate")
	if err == nil {
		t.Fatal("gate must fail with s1 pending")
	}

	out = h.mustRun("", "step", "next")
	assertContains(t, out, "all steps reviewed")

	out = h.mustRun("", "status", "--gate")
	assertContains(t, out, "✓ s1", "~ s2", "core 1/2 reviewed (0 skipped, 1 stale)", "hotspots 1/1", "boilerplate 1 files", "generated 1 files", "1 blocker", "gate: passed")

	out = h.mustRun("", "step", "goto", "s2")
	assertContains(t, out, "s2 2/2 [stale]")
}

func TestStepSkip(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	if _, err := h.run("", "step", "skip"); err == nil {
		t.Fatal("skip without reason must fail")
	}
	out := h.mustRun("", "step", "skip", "--reason", "trivial")
	assertContains(t, out, "s2 2/2 [pending]")
	out = h.mustRun("", "step", "show", "s1")
	assertContains(t, out, "[skipped]", "skipped: trivial")
}

func TestNotesAndResolve(t *testing.T) {
	h := newHarness(t)
	h.mustRun("", "init")
	h.mustRun(goodPlan, "plan", "set")
	out := h.mustRun("", "note", "add", "--file", "api/transfer.go", "--line", "4", "guard", "for", "negatives")
	assertContains(t, out, "note s1 api/transfer.go:4")
	out = h.mustRun("", "step", "show")
	assertContains(t, out, "note api/transfer.go:4: guard for negatives")

	h.mustRun("", "comment", "add", "--file", "api/transfer.go", "--lines", "5", "--severity", "nit", "x")
	out = h.mustRun("", "comment", "resolve", "1")
	assertContains(t, out, "comment #1 resolved")
	out = h.mustRun("", "comment", "list")
	assertContains(t, out, "#1 nit s1 api/transfer.go:5  x  [resolved]")
}
